on: [push, workflow_dispatch]
name: build
jobs:
  build:
    name: Tacview Filter
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: haskell-actions/setup@v2
        id: build
        with:
          ghc-version: "9.10.3"
      - run: |
          cabal build -O2
          cabal install -O2 --install-method copy --installdir _build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Executables
          path: _build/

      - name: Release (if a new version is tagged)
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            _build/tacview-filter.exe
            _build/tacview-replay.exe
            _build/tacview-server.exe
            _build/tacview-stats.exe
